# Generated by Django 3.2.18 on 2023-06-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creature_type', models.CharField(choices=[('POKEMON', 'Pokemon'), ('DIGIMON', 'Digimon')], max_length=100)),
                ('img_url', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name', 'creature_type')},
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(choices=[('NORMAL', 'Normal'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('GRASS', 'Grass'), ('ELECTRIC', 'Electric'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('POISON', 'Poison'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('DRAGON', 'Dragon'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=10)),
                ('type2', models.CharField(choices=[('NORMAL', 'Normal'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('GRASS', 'Grass'), ('ELECTRIC', 'Electric'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('POISON', 'Poison'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('DRAGON', 'Dragon'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=10)),
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creatures.creature')),
            ],
        ),
        migrations.CreateModel(
            name='Digimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('FRESH', 'Fresh'), ('IN TRAINING', 'In Training'), ('ROOKIE', 'Rookie'), ('CHAMPION', 'Champion'), ('ULTIMATE', 'Ultimate'), ('ARMOR', 'Armor'), ('MEGA', 'Mega')], max_length=12)),
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creatures.creature')),
            ],
        ),
    ]
