# Generated by Django 3.2.18 on 2023-06-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0002_auto_20230620_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
